name: Frontend Checks & Security

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: false

env:
  NODE_VERSION: "20"
  PNPM_VERSION: "8"

jobs:
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_call' || inputs.run_security
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run security audit
        run: bunx audit

  deps:
    name: Dependencies Check
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_call' || inputs.run_deps
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Check dependencies
        run: |
          bun install
          bunx depcheck
          bunx npm-check-updates

  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_call' || inputs.run_lint
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun run tsc --noEmit

      - name: Lint code
        run: |
          bunx eslint . --max-warnings 0
          bunx prettier --check .

  test:
    name: Test
    runs-on: ubuntu-latest
    if: always()
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run tests with coverage
        run: bun test --coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: coverage/
          retention-days: 14

  accessibility:
    name: Accessibility Check
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_call' || inputs.run_accessibility
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build Storybook
        run: bun run build-storybook

      - name: Run accessibility tests
        run: |
          bunx start-storybook -p 6006 -c .storybook &
          sleep 10
          bunx axe-storybook
